### ISSUE TITLE
How to config for multi memcached servers

### ISSUE THREAD

**Issue by kk17** [igorbolic/memcached-spring-boot#1]
I want to know how to config for multi memcached servers?

**Comment by igorbolic** [comment]
Currently there is no support for specifying multiple memcached servers. I am planning to add this option with the first release of the library.

If you are using AWS ElastiCache there is support for _Auto Discovery_ by specifying `memcached.cache.mode=dynamic` in your configuration file. It will allow for the client to automatically identify all of the nodes in a cache cluster.

**Comment by igorbolic** [comment]
The multi-server configuration is now supported with the library. Please check the documentation in [README.md](https://github.com/igorbolic/memcached-spring-boot/blob/master/README.md).
In the next few days the **1.0.0** version of the library will be available publicly, so you can try it out. Therefore, I'm closing the issue.
