### ISSUE TITLE
spring.cache.type=none is not being honored 

### ISSUE THREAD

**Issue by sekhrivijay** [igorbolic/memcached-spring-boot#4]
Setting cache type to none should  disable the caching .
```
spring:
  cache:
    type: none

```
However, I tested that the values are still getting cached.

**Comment by igorbolic** [comment]
Thank you for reporting an issue. Most probably, this will be addressed in the next release of the library. The release is planned for the next week.

**Comment by igorbolic** [comment]
The issue has been fixed with the version **1.0.1**. The new version is available on Maven Central and JCenter.
